# Generated by Django 4.0.6 on 2022-07-21 10:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GetIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('browser', models.CharField(max_length=255)),
                ('device', models.CharField(max_length=255)),
                ('device_type', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
