# Generated by Django 4.0.6 on 2022-07-21 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0002_getip'),
    ]

    operations = [
        migrations.AddField(
            model_name='getip',
            name='visited_at',
            field=models.CharField(default='index', max_length=255),
            preserve_default=False,
        ),
    ]
