# Generated by Django 4.0.6 on 2022-07-22 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0003_getip_visited_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(max_length=255)),
                ('about', models.TextField(max_length=255)),
                ('birthday', models.DateField(max_length=6)),
                ('degree', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=55)),
                ('phone', models.CharField(max_length=255)),
                ('github', models.CharField(max_length=255)),
                ('linkedin', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('short_desp', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
                ('keyword', models.CharField(max_length=255)),
                ('img', models.ImageField(upload_to='blog_img')),
                ('body', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=55)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=255)),
                ('university', models.CharField(max_length=255)),
                ('start_year', models.CharField(max_length=6)),
                ('end_year', models.CharField(max_length=6)),
                ('desp', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
        migrations.AlterField(
            model_name='getip',
            name='visited_at',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
