# Generated by Django 4.0.6 on 2022-07-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0005_experience_register_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='address',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
