# Generated by Django 4.0.6 on 2022-07-23 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0006_register_address_register_city_register_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='dob',
            field=models.CharField(max_length=15),
        ),
    ]
