# Generated by Django 4.0.6 on 2022-07-27 17:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0007_alter_register_dob'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('specialization', models.CharField(max_length=255)),
                ('hero_img', models.ImageField(upload_to='uploads')),
                ('cv_file', models.FileField(upload_to='info')),
                ('embedded_link', models.CharField(max_length=255)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.today)),
            ],
        ),
    ]
