# Generated by Django 4.0.6 on 2022-08-16 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0008_hero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='about',
            field=models.TextField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='about',
            name='degree',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='about',
            name='experience',
            field=models.CharField(default='', max_length=55),
        ),
        migrations.AlterField(
            model_name='about',
            name='github',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='linkedin',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='phone',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='about',
            name='specialization',
            field=models.CharField(default='', max_length=255),
        ),
    ]
