# Generated by Django 4.0.6 on 2023-02-27 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0010_alter_about_updated_at_alter_blogs_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='birthday',
            field=models.TextField(),
        ),
    ]
